from typing import Final

# api-spec §0 에러 code 표. 와이어 값 동결 — rename/삭제 금지.
INVALID_REQUEST: Final = "INVALID_REQUEST"
UNAUTHORIZED: Final = "UNAUTHORIZED"
TOKEN_EXPIRED: Final = "TOKEN_EXPIRED"
FORBIDDEN: Final = "FORBIDDEN"
STOCK_NOT_FOUND: Final = "STOCK_NOT_FOUND"
DATA_NOT_FOUND: Final = "DATA_NOT_FOUND"
CONFLICT: Final = "CONFLICT"
INSUFFICIENT_DATA: Final = "INSUFFICIENT_DATA"
INTERNAL_ERROR: Final = "INTERNAL_ERROR"
